spring.application.name=Holonode
spring.datasource.url=jdbc:sqlite:holonode.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# JWT and Origins configuration. Must be set in environment variables
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
allowed.origins=${ALLOWED_ORIGINS}